#!/bin/sh
test -d $HOME/.local/packages || mkdir -p  $HOME/.local/packages 
test -d $HOME/.local/bin || mkdir -p  $HOME/.local/bin 
test -d $HOME/.local/packages/toolbox || { 
	cd  $HOME/.local/packages 
	curl -L -O -J http://www.hesabu.net/dk0/toolbox.zip 
	unzip toolbox.zip 
}

test -x $HOME/.local/bin/toolbox || { 
	cat>$HOME/.local/bin/toolbox <<-EOF
		export PATH=~/.local/packages/toolbox:\$PATH
		toolbox 2>/dev/null &
	EOF
	chmod a+x $HOME/.local/bin/toolbox 
}

which toolbox  

