#!/bin/sh
#sudo apt-get -y install libusb-1.0-0-dev libudev-dev mercurial
#pip install --user -U jsonschema
#export PATH=${PATH#/home/student/anaconda3/bin:}
conda create -n py27 python=2.7
source activate py27
sudo apt-get install -y mercurial
pip install --user -U 'colorama>=0.3.3'
pip install --user -U 'PySerial>=2.7'
pip install --user -U 'PrettyTable>=0.7.2'
pip install --user -U 'Jinja2>=2.7.3'
pip install --user -U 'IntelHex>=1.3'
pip install --user -U 'junit-xml'
pip install --user -U 'pyYAML'
pip install --user -U 'requests'
pip install --user -U 'mbed-ls>=0.2.13'
pip install --user -U 'mbed-host-tests>=1.1.2'
pip install --user -U 'mbed-greentea>=0.2.24'
pip install --user -U 'beautifulsoup4>=4'
pip install --user -U 'fuzzywuzzy>=0.11'
pip install --user -U pyOCD 
pip install --user -U mbed-cli
mbed config -G GCC_ARM_PATH ~/.local/packages/gcc-arm/bin
#git clone https://github.com/davidkendall/blinky-mbed
mbed import https://github.com/davidkendall/blinky-mbed
cd blinky-mbed
#mbed new .
#mbed deploy
mbed target K64F
mbed toolchain GCC_ARM
mbed compile --flash

