#!/bin/sh
sudo apt-get -y install libusb-1.0-0-dev libudev-dev mercurial
pip install --user -U jsonschema
pip install --user -U pyOCD 
pip install --user -U mbed-cli
mbed config -G GCC_ARM_PATH ~/.local/packages/gcc-arm/bin
#git clone https://github.com/davidkendall/blinky-mbed
mbed import https://github.com/davidkendall/blinky-mbed
cd blinky-mbed
#mbed new .
#mbed deploy
mbed target K64F
mbed toolchain GCC_ARM
mbed compile --flash
